/*
Ory Kratos API

Documentation for all public and administrative Ory Kratos APIs. Public and administrative APIs are exposed on different ports. Public APIs can face the public internet without any protection while administrative APIs should never be exposed without prior authorization. To protect the administative API port you should use something like Nginx, Ory Oathkeeper, or any other technology capable of authorizing incoming requests. 

API version: v0.8.2-alpha.1
Contact: hi@ory.sh
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SuccessfulSelfServiceLoginBrowser The Response for Login Flows via API
type SuccessfulSelfServiceLoginBrowser struct {
	Session Session `json:"session"`
	// The Session Token  A session token is equivalent to a session cookie, but it can be sent in the HTTP Authorization Header:  Authorization: bearer ${session-token}  The session token is only issued for API flows, not for Browser flows!
	SessionToken *string `json:"session_token,omitempty"`
}

// NewSuccessfulSelfServiceLoginBrowser instantiates a new SuccessfulSelfServiceLoginBrowser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessfulSelfServiceLoginBrowser(session Session) *SuccessfulSelfServiceLoginBrowser {
	this := SuccessfulSelfServiceLoginBrowser{}
	this.Session = session
	return &this
}

// NewSuccessfulSelfServiceLoginBrowserWithDefaults instantiates a new SuccessfulSelfServiceLoginBrowser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessfulSelfServiceLoginBrowserWithDefaults() *SuccessfulSelfServiceLoginBrowser {
	this := SuccessfulSelfServiceLoginBrowser{}
	return &this
}

// GetSession returns the Session field value
func (o *SuccessfulSelfServiceLoginBrowser) GetSession() Session {
	if o == nil {
		var ret Session
		return ret
	}

	return o.Session
}

// GetSessionOk returns a tuple with the Session field value
// and a boolean to check if the value has been set.
func (o *SuccessfulSelfServiceLoginBrowser) GetSessionOk() (*Session, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Session, true
}

// SetSession sets field value
func (o *SuccessfulSelfServiceLoginBrowser) SetSession(v Session) {
	o.Session = v
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *SuccessfulSelfServiceLoginBrowser) GetSessionToken() string {
	if o == nil || o.SessionToken == nil {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessfulSelfServiceLoginBrowser) GetSessionTokenOk() (*string, bool) {
	if o == nil || o.SessionToken == nil {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *SuccessfulSelfServiceLoginBrowser) HasSessionToken() bool {
	if o != nil && o.SessionToken != nil {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *SuccessfulSelfServiceLoginBrowser) SetSessionToken(v string) {
	o.SessionToken = &v
}

func (o SuccessfulSelfServiceLoginBrowser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["session"] = o.Session
	}
	if o.SessionToken != nil {
		toSerialize["session_token"] = o.SessionToken
	}
	return json.Marshal(toSerialize)
}

type NullableSuccessfulSelfServiceLoginBrowser struct {
	value *SuccessfulSelfServiceLoginBrowser
	isSet bool
}

func (v NullableSuccessfulSelfServiceLoginBrowser) Get() *SuccessfulSelfServiceLoginBrowser {
	return v.value
}

func (v *NullableSuccessfulSelfServiceLoginBrowser) Set(val *SuccessfulSelfServiceLoginBrowser) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessfulSelfServiceLoginBrowser) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessfulSelfServiceLoginBrowser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessfulSelfServiceLoginBrowser(val *SuccessfulSelfServiceLoginBrowser) *NullableSuccessfulSelfServiceLoginBrowser {
	return &NullableSuccessfulSelfServiceLoginBrowser{value: val, isSet: true}
}

func (v NullableSuccessfulSelfServiceLoginBrowser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessfulSelfServiceLoginBrowser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


